apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: backend
spec:
  containers:
    - name: backend
      image: "hstenzel/nodejs-hostname:latest"
      stdin: true
      tty: true
      ports:
        - name: web-app
          containerPort: 8080
